/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.etlsolutions.examples.ha.pojo;
// Generated 10-Nov-2015 10:41:48 by Hibernate Tools 4.3.1

import com.etlsolutions.examples.data.api.AmexcardPayment;
import com.etlsolutions.examples.data.spi.AmexcardPaymentSpi;
import com.etlsolutions.examples.ha.control.QueryNames;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.Hibernate;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * The AmexcardPaymentPojo class is generated automatically then modified
 * manually.
 *
 * @author Zhipeng Chang
 *
 * @since 1.0.0
 *
 * @version 1.0.0 - generated by NetBeans.
 * @version 1.0.1 - Add implementation of CardPaymentSpi.
 * @version 2.0.0 - Add named query "findAmexcardPayments".
 * @version 2.1.0 - Implement equals and hashCode methods.
 */
@Entity
@Table(name = "amexcard_payment", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "payment_detail_id"))
@NamedQueries({
    @NamedQuery(name = QueryNames.findAmexcardPayments, query = "from AmexcardPaymentPojo")
})
public class AmexcardPaymentPojo implements Serializable, AmexcardPaymentSpi<PaymentDetailPojo, PersonAddressLinkPojo> {

    private static final long serialVersionUID = 538625421248956357L;

    @Id
    @Column(name = "payment_id", unique = true, nullable = false)
    private int id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "payment_detail_id", referencedColumnName = "payment_detail_id", unique = true),
        @JoinColumn(name = "payment_type", referencedColumnName = "payment_type")})
    private PaymentDetailPojo paymentDetail;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_address_link_id")
    private PersonAddressLinkPojo personAddressLink;
    
    @Column(name = "card_number", nullable = false, length = 15)
    private String cardNumber;
    
    @Column(name = "security_code", nullable = false, length = 4)
    private String securityCode;
    
    @Temporal(TemporalType.DATE)
    @Column(name = "expire_date", nullable = false, length = 13)
    private Date expireDate;

    public AmexcardPaymentPojo() {
    }

    public AmexcardPaymentPojo(int id, PaymentDetailPojo paymentDetail, String cardNumber, String securityCode, Date expireDate) {
        this.id = id;
        this.paymentDetail = paymentDetail;
        this.cardNumber = cardNumber;
        this.securityCode = securityCode;
        this.expireDate = expireDate;
    }

    public AmexcardPaymentPojo(int id, PaymentDetailPojo paymentDetail, PersonAddressLinkPojo personAddressLink, String cardNumber, String securityCode, Date expireDate) {
        this.id = id;
        this.paymentDetail = paymentDetail;
        this.personAddressLink = personAddressLink;
        this.cardNumber = cardNumber;
        this.securityCode = securityCode;
        this.expireDate = expireDate;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(int id) {
        this.id = id;
    }

    @Override
    public PaymentDetailPojo getPaymentDetail() {
        return this.paymentDetail;
    }

    @Override
    public void setPaymentDetail(PaymentDetailPojo paymentDetail) {
        this.paymentDetail = paymentDetail;
    }

    @Override
    public PersonAddressLinkPojo getPersonAddressLink() {
        return this.personAddressLink;
    }

    @Override
    public void setPersonAddressLink(PersonAddressLinkPojo personAddressLink) {
        this.personAddressLink = personAddressLink;
    }

    @Override
    public String getCardNumber() {
        return this.cardNumber;
    }

    @Override
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    @Override
    public String getSecurityCode() {
        return this.securityCode;
    }

    @Override
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }

    @Override
    public Date getExpireDate() {
        return this.expireDate;
    }

    @Override
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + this.id;
        return hash;
    }

    @Override
    @SuppressWarnings("EqualsWhichDoesntCheckParameterClass")
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        //This code should be kept to show a method to compare the class. 
        //For Hibernate directly comparison of the class names is no good since 
        //its children should be considered as equals when their IDs are the same. 
        if (Hibernate.getClass(this) != Hibernate.getClass(obj)) {
            return false;
        }

        final AmexcardPaymentPojo other = (AmexcardPaymentPojo) obj;
        return this.id == other.id;
    }

    @Override
    public boolean hasSameConstraint(AmexcardPayment constraintable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean hasSameParameters(AmexcardPayment constraintable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
