/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.etlsolutions.examples.ha.pojo;
// Generated 10-Nov-2015 10:41:48 by Hibernate Tools 4.3.1

import com.etlsolutions.examples.data.api.Review;
import com.etlsolutions.examples.data.spi.ReviewSpi;
import com.etlsolutions.examples.ha.control.QueryNames;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.Hibernate;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * The ReviewPojo generated class is generated automatically then modified manually.
 *
 * @author Zhipeng Chang
 * 
 * @since 1.0.0
 * 
 * @version 1.0.0 - generated by NetBeans.
 * @version 1.0.1 - Add the implementation of ReviewSpi.
 */
@Entity
@Table(name = "review", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"reviewer_id", "item_common_detail_id"}))
@NamedQueries({
        @NamedQuery(name = QueryNames.findReviews, query = "from ReviewPojo")
})
public class ReviewPojo implements Serializable, ReviewSpi<ItemCommonDetailPojo, ReviewerPojo> {

    private static final long serialVersionUID = 51610971448552264L;
    
    @Id
    @Column(name = "review_id", unique = true, nullable = false)
    private int id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_common_detail_id")
    private ItemCommonDetailPojo itemCommonDetail;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewer_id")
    private ReviewerPojo reviewer;
    
    @Column(name = "review_ranking")
    private Integer reviewRanking;
    
    @Column(name = "review_text", length = 4000)
    private String reviewText;

    public ReviewPojo() {
    }

    public ReviewPojo(int id) {
        this.id = id;
    }

    public ReviewPojo(int id, ItemCommonDetailPojo itemCommonDetail, Integer reviewRanking, String reviewText) {
        this.id = id;
        this.itemCommonDetail = itemCommonDetail;
        this.reviewRanking = reviewRanking;
        this.reviewText = reviewText;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(int id) {
        this.id = id;
    }

    @Override
    public ItemCommonDetailPojo getItemCommonDetail() {
        return this.itemCommonDetail;
    }

    @Override
    public void setItemCommonDetail(ItemCommonDetailPojo itemCommonDetail) {
        this.itemCommonDetail = itemCommonDetail;
    }

    @Override
    public ReviewerPojo getReviewer() {
        return reviewer;
    }

    @Override
    public void setReviewer(ReviewerPojo reviewer) {
        this.reviewer = reviewer;
    }
    
    @Override
    public int getReviewRanking() {
        return this.reviewRanking;
    }

    @Override
    public void setReviewRanking(int reviewRanking) {
        this.reviewRanking = reviewRanking;
    }

    @Override
    public String getReviewText() {
        return this.reviewText;
    }

    @Override
    public void setReviewText(String reviewText) {
        this.reviewText = reviewText;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 19 * hash + this.id;
        return hash;
    }

    @Override
    @SuppressWarnings("EqualsWhichDoesntCheckParameterClass")
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        
        //This code should be kept to show a method to compare the class. 
        //For Hibernate directly comparison of the class names is no good since 
        //its children should be considered as equals when their IDs are the same. 
        if (Hibernate.getClass(this) != Hibernate.getClass(obj)) {
            return false;
        }
        
        final ReviewPojo other = (ReviewPojo) obj;
        return this.id == other.id;
    }

    @Override
    public boolean hasSameConstraint(Review constraintable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean hasSameParameters(Review constraintable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
