/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.etlsolutions.examples.ha.pojo;
// Generated 10-Nov-2015 10:41:48 by Hibernate Tools 4.3.1

import com.etlsolutions.examples.data.api.ItemCommonDetail;
import com.etlsolutions.examples.data.api.Wishlist;
import com.etlsolutions.examples.data.spi.WishlistSpi;
import com.etlsolutions.examples.ha.control.QueryNames;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.Hibernate;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * The WishlistPojo class is generated automatically then modified manually.
 *
 * @author Zhipeng Chang
 * 
 * @since 1.0.0
 * 
 * @version 1.0.0 - generated by NetBeans.
 * @version 1.0.1 - Add implementation of WishlistSpi.
 * @version 2.0.0 - Add named query"findWishlists".
 */
@Entity
@Table(name = "wishlist", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {"customer_id", "wishlist_name"}))
@NamedQueries({
        @NamedQuery(name = QueryNames.findWishlists, query = "from WishlistPojo")
})
public class WishlistPojo implements Serializable, WishlistSpi<CustomerPojo> {

    private static final long serialVersionUID = 161562973537210035L;
    
    @Id
    @Column(name = "wishlist_id", unique = true, nullable = false)
    private int id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private CustomerPojo customer;
    
    @Column(name = "wishlist_name", nullable = false, length = 100)
    private String name;
    
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "wishlist_item_link", schema = "public", joinColumns = {
        @JoinColumn(name = "wishlist_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "item_common_detail_id", nullable = false, updatable = false)})
    private Set<ItemCommonDetail> itemCommonDetails = new HashSet<>(30);

    public WishlistPojo() {
    }

    public WishlistPojo(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public WishlistPojo(int id, CustomerPojo customer, String name, Set<ItemCommonDetail> itemCommonDetails) {
        this.id = id;
        this.customer = customer;
        this.name = name;
        this.itemCommonDetails = itemCommonDetails;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(int id) {
        this.id = id;
    }

    @Override
    public CustomerPojo getCustomer() {
        return this.customer;
    }

    @Override
    public void setCustomer(CustomerPojo customer) {
        this.customer = customer;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    public Set<ItemCommonDetail> getItemCommonDetails() {
        return this.itemCommonDetails;
    }

    public void setItemCommonDetails(Set<ItemCommonDetail> itemCommonDetails) {
        this.itemCommonDetails = itemCommonDetails;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + this.id;
        return hash;
    }

    @Override
    @SuppressWarnings("EqualsWhichDoesntCheckParameterClass")
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        //This code should be kept to show a method to compare the class. 
        //For Hibernate directly comparison of the class names is no good since 
        //its children should be considered as equals when their IDs are the same. 
        if (Hibernate.getClass(this) != Hibernate.getClass(obj)) {
            return false;
        }


        final WishlistPojo other = (WishlistPojo) obj;
        return this.id == other.id;
    } 

    @Override
    public boolean hasSameConstraint(Wishlist constraintable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean hasSameParameters(Wishlist constraintable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
