//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 11:32:10 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/etlsolutions/examples/spring/webservices/accountservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.etlsolutions.examples.spring.webservices.accountservice;
